### ISSUE TITLE
Incorrect code generation for enum cases containing numbers

### ISSUE THREAD

**Issue by hispanico94** [apollographql/apollo-ios#2749]
### Summary

We started migration to Apollo 1.0.5 (from 0.51.2), we ran the apollo-ios-cli code generation tool and then we got several compiler errors because the new tool generated a Swift enum where the cases names differs from what the 0.51.2 code generation tool generates. 

If the graphql enum case name contains all uppercase letters and numbers (e.g `BEFORE1940`)  then only the first letter of the generated Swift enum case is lowercased (`.bEFORE1940`) , all the other letters remains uppercased. Apollo 0.51.2 code generation would lowercase all the letters of the enum case name (`.before1940`).

### Version

1.0.5

### Steps to reproduce the behavior

Given the following graphql enum

```graphql
enum HomeConstructionPeriod {
  BEFORE1940
  BEFORE1970
  DECADE1940
  DECADE1950
  DECADE1960
  DECADE1970
  DECADE1980
  DECADE1990
  DECADE2000
  DECADE2010
  DECADE2020
  UNKNOWN
}
```

Apollo 1.0.5 generates

```swift
enum HomeConstructionPeriod: String, EnumType {
    case bEFORE1940 = "BEFORE1940"
    case bEFORE1970 = "BEFORE1970"
    case dECADE1940 = "DECADE1940"
    case dECADE1950 = "DECADE1950"
    case dECADE1960 = "DECADE1960"
    case dECADE1970 = "DECADE1970"
    case dECADE1980 = "DECADE1980"
    case dECADE1990 = "DECADE1990"
    case dECADE2000 = "DECADE2000"
    case dECADE2010 = "DECADE2010"
    case dECADE2020 = "DECADE2020"
    case unknown = "UNKNOWN"
  }
```

While Apollo 0.51.2 generates

```swift
 public enum HomeConstructionPeriod: RawRepresentable, Equatable, Hashable, CaseIterable, Apollo.JSONDecodable, Apollo.JSONEncodable {
    public typealias RawValue = String
    case before1940
    case before1970
    case decade1940
    case decade1950
    case decade1960
    case decade1970
    case decade1980
    case decade1990
    case decade2000
    case decade2010
    case decade2020
    case unknown

    // ... Other code omitted ...
}
```

### Anything else?

Our naming convention for graphql enums is using snake_case with UPPERCASED words for the cases (e.g. `GENERIC_ERROR`). In the Swift codebase we follow the classic lowercase words and camelCase (e.g. `.genericError`).

All the other generated Swift enums are consistent between Apollo 1.0.5 and 0.51.2, with lowercased words and camelCase. The enum reported above is the only one we have that also contains numbers and the only one that presents the described issue with the code generation.

**Comment by calvincestari** [comment]
Hi 👋 - I think this is probably fixed with #2745. You should try that branch to see if it resolved the issue; it'll go out in the next version.

**Comment by hispanico94** [comment]
Hi @calvincestari, thanks for the quick response. I tried regenerating the enum using the `fix/enum-case-conversion-strategy` branch you suggested, but sadly it didn't solve the issue. The generated enum is the same. I removed the old generated file and made sure to reinstall the CLI, the problem persists.

**Comment by calvincestari** [comment]
@hispanico94 - this is fixed and available on the `main` branch. It will be included in the next release.
