### ISSUE TITLE
Apollo 1.1.0 @testable import in Test Mocks compilation error

### ISSUE THREAD

**Issue by SzymonMatysik** [apollographql/apollo-ios#2933]
### Summary

While compiling project I've expected issue with ApolloAPI in TestMock.swift, second line: 
`Module 'ApolloAPI' was not compiled for testing`.

Dropping to 1.0.7 erases the issue.
I've tried on Xcode 14.2 and 14.3 - same results.

### Version

1.1.0

### Steps to reproduce the behavior

Upgrade Apollo from 1.0.7 to 1.1.0 and try to compile.

### Logs

```shell
Module 'ApolloAPI' was not compiled for testing
```

### Anything else?

![Screenshot 2023-04-05 at 15 31 39](https://user-images.githubusercontent.com/40841695/230095987-8aa5357e-b9b5-49cf-8843-3b07a4b0ea9c.png)

**Comment by AnthonyMDev** [comment]
Hmmm interesting! Thanks for the report. How are you including Apollo? Are you using SPM in an Xcode Project, or is your project defined with a `Package.swift` file?

**Comment by AnthonyMDev** [comment]
Thanks for the info! I'll look into how to correct this and get back to you ASAP

**Comment by AnthonyMDev** [comment]
@SzymonMatysik I'm not able to reproduce this in a unit test target. Are you accidentally linking `ApolloTestSupport` to your actual application targets? It should only be linked to your unit test targets.

**Comment by calvincestari** [comment]
This was fixed in https://github.com/apollographql/apollo-ios/pull/2937.

**Comment by SzymonMatysik** [comment]
@AnthonyMDev You were right about accidentally linking ApolloTestSupport into main app target, nevertheless when I deleted it and added into UnitTest target only the issue persists. `Module 'ApolloAPI' was not compiled for testing`

I've checked on 1.1.2, still with no luck

**Comment by calvincestari** [comment]
@SzymonMatysik are there no other warnings or errors in the build log? Are you able to replicate this in a separate project that could be shared with us?

**Comment by Tulleb** [comment]
In our case, we were using Mocks into our internal build release. Looks like we can't release this target anymore because of the `@testable` 😵

**Comment by wiedem** [comment]
We've got the same issue and it is not solved with https://github.com/apollographql/apollo-ios/pull/2937

The reason in our case is that Apollo is a transient dependency of another Swift package.
In this case testable Imports don't seem to work and you get the error message 

> Module 'ApolloAPI' was not compiled for testing

**Comment by calvincestari** [comment]
> The reason in our case is that Apollo is a transient dependency of another Swift package (a dependency of a dependency).
In this case testable Imports don't seem to work and you get the error message

This is a good pointer in the right direction - thanks you!

@SzymonMatysik, @Tulleb - is there anything similar in the way you're linking to the Apollo library?

**Comment by wiedem** [comment]
@calvincestari what's the reason this issue was closed?

It seems I've found one cause for the issue:
In our case we're using a separate build configuration for the test target.

<img width="510" alt="BuildConfiguration" src="https://user-images.githubusercontent.com/18583580/236506267-174108de-8a40-459e-9567-2160f0b7ec33.png">

Switching to the _Debug_ configuration gets rid of the build error but is not really an option for us since we need a separate build configuration for tests.

I can also reproduce this 100%, when I switch back to the testing configuration, the error occurs again:
<img width="382" alt="TestMock" src="https://user-images.githubusercontent.com/18583580/236507150-04a52c61-b8bc-487b-b104-e0f930437e12.png">

I have also tried it by simply cloning the debug configuration and thus using an identical configuration with a different name. This alone is enough for this error to occur.

**Comment by wiedem** [comment]
The root cause of the problem seems to be this:
[Update SPM to support custom configuration names](https://forums.swift.org/t/update-spm-to-support-custom-configuration-names/43075)

When a Swift package is compiled there are only two configurations that are used: _Debug_ or _Release_. If a configuration name is unknown, _Release_ is used as a fallback.

So if you use a different build configuration in Xcode, it seems the Apollo targets are all built with a release configuration. Which should ultimately lead to the described problem.

**Comment by wiedem** [comment]
And to leave a solution here that might help others:
In our case, renaming the configuration from "Testing" to "Debug_Testing" solved the issue.

**Comment by calvincestari** [comment]
> @calvincestari what's the reason this issue was closed?

It was closed because it was believed to have been fixed - https://github.com/apollographql/apollo-ios/issues/2933#issuecomment-1499770485.

@testable is not usable in anything other than Debug builds. or those specifically marked for 'testing'; Release builds violate both of those and it seems there are some deficiencies in SPM that allows for custom build configurations that would resolve this.

It looks like we can probably remove `@testable` from the `ApolloAPI` import but not from the `Apollo` import because of the need for the `internal` scoped `GraphQLExecutor` class. Let's also not forget the intention behind `ApolloTestSupport` which is for testing; I like that Release builds are prevented from shipping code that should never make it into production. The shortfall in SPM build configurations is an annoying limitation but not something I want to necessarily work around.

To be frank, with the introduction of selection set initializers in `1.1` the future of test mocks is uncertain. Being schema-based they offer a different type of testing ability but the value is diluted now.

> And to leave a solution here that might help others:
> In our case, renaming the configuration from "Testing" to "Debug_Testing" solved the issue.

I haven't tried this myself but thank you for sharing this to help others that might be facing the same issue.

**Comment by wiedem** [comment]
> @testable is not usable in anything other than Debug builds. or those specifically marked for 'testing';

Just to be clear, our testing configuration was not a release configuration, but a debug configuration. The problem of the SPM arose solely from the configuration name.

That `@testable` should not work for release builds is out of question.

**Comment by rickpasetto** [comment]
@calvincestari thank you for the reply. Question, then: How do you recommend using ApolloTestSupport for Xcode Previews then?  It's awfully convenient to use Apollo Mocks for forging data to show in Xcode Previews.  Just wrapping the `import ApolloTestSupport` in `#if DEBUG` won't work or be sufficient, correct?  Any hints?  Thanks!
