### ISSUE TITLE
ApolloSQLite doesn't compile on Xcode 16 due to `Expression` symbol clash with new `Foundation.Expression`

### ISSUE THREAD

**Issue by cameroncooke** [apollographql/apollo-ios#3394]
### Summary

When compiling on Xcode 16 the following error `'Expression' is ambiguous for type lookup in this context` is raised.

<img width="1419" alt="Screenshot 2024-06-11 at 13 50 02" src="https://github.com/apollographql/apollo-ios/assets/630601/2eede2d9-1d73-4553-95a8-039f49c72cf7">

### Version

1.12.2

### Steps to reproduce the behavior

Build Apollo for iOS on Xcode 16

### Logs

```shell
Showing Recent Issues
.../SourcePackages/checkouts/apollo-ios/Sources/ApolloSQLite/SQLiteDotSwiftDatabase.swift:11:26: 'Expression' is ambiguous for type lookup in this context
```

**Comment by cameroncooke** [comment]
Is see this is already fixed on Main branch 🎉

**Comment by calvincestari** [comment]
Hi @cameroncooke - this was fixed yesterday with PR https://github.com/apollographql/apollo-ios-dev/pull/386. It's only in `main` for now as it has not gone out in a release yet though.

**Comment by lexuanquynh** [comment]
@calvincestari Is there a way to quickly use the branch you fixed without waiting for the release?

**Comment by AndyBettisLush** [comment]
I'm still seeing this problem with release 1.15.1. Is there a fix? Xcode 16.0 running on Sequoia 15.0

**Comment by lexuanquynh** [comment]
@AndyBettisLush  thank you. I have updated it to 1.15.1 and fixed it.

**Comment by AndyBettisLush** [comment]
@lexuanquynh I'm still seeing it. I've tried changing to 1.15.0 and back to 1.15.1, reloading the packages, quitting & restarting Xcode, still no joy. Any suggestions?

**Comment by calvincestari** [comment]
Glad you both have it working, let us know if you have any more issues with this error.

**Comment by lexuanquynh** [comment]
@AndyBettisLush 
I set it to 1.15.1 as shown in the image. Then I used the clear cache feature of the Swift package and it updated the exact version as shown in the second image.

<img width="861" alt="Screenshot 2024-09-18 at 21 40 16" src="https://github.com/user-attachments/assets/94c42a26-b839-4d9a-8d9a-2d296a87d4d1">

<img width="275" alt="Screenshot 2024-09-18 at 21 41 45" src="https://github.com/user-attachments/assets/2747d62f-de3c-4c4a-b57e-2b797085cd3c">
