### ISSUE TITLE
Unable to build my Swift project after Swift 5 update

### ISSUE THREAD

**Issue by chrisabbod** [apollographql/apollo-ios#495]
Ever since the update to Swift 5 I get the following error when I build:

Cannot assign value of type 'EnumeratedSequence<[Key]>.Iterator' to type 'EnumeratedSequence<IndexingIterator<Array<Key>>>.Iterator'

This error occurs in Collections.swift line 65

init(base: GroupedSequence<Key, Value>) {
    self.base = base
    keyIterator = base.keys.enumerated().makeIterator()  //Line with error
  }

**Comment by victormihaita** [comment]
The pod has to be updated to support swift 5.0. This should be done quite soon. I’m also waiting for this :)

**Comment by ultranano** [comment]
the same problem... need a pod update with swift 5.0 support.

**Comment by martijnwalraven** [comment]
This should be fixed in 0.10.0.

**Comment by chrisabbod** [comment]
Is there a timeline for the release of 0.10.0?

**Comment by martijnwalraven** [comment]
@chrisabbod I just released it!

**Comment by chrisabbod** [comment]
Thank you so much for the support!!

**Comment by svsharsha** [comment]
Im still facing this issue now. I've tried in both 4.2 and 5.0 swift versions.

**Comment by designatednerd** [comment]
@svsharsha Can you please open a new issue and let us know a) What version of the Apollo library you're using and b) What version of Xcode you're using? Thanks.
